apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-flask1
  template:
    metadata:
      labels:
        app: python-flask1
    spec:
      containers:
        - name: python-app1
          image: nithyaks/python-flask-demo:ver2
          resources:
            limits:
              memory: "2Gi"
              cpu: "500m"
            requests:
              memory: "1Gi"
              cpu: "200m"
